export const GET_REGISTER_USER = 'GET_REGISTER_USER';
export const SET_REGISTER_USER = 'SET_REGISTER_USER';
export const RESET_STATE = 'RESET_STATE';
export const SET_ARTIST_REGISTER_USER = 'SET_ARTIST_REGISTER_USER';
export const CURRENT_USER = 'CURRENT_USER';
export const GENRE_LIST = 'GENRE_LIST';
